server:
  port: 8081
  servlet:
    context-path: /dev/api/${spring.application.name}

security:
  jwt:
    secret-key: "t9RVbZHpQPL36Jxo6oUZIfUc6Sxo1DJn"  # Plain text secret key
    expiration-time: 60000
    refresh-expiration-time: 180000

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
     url: jdbc:mysql://localhost:3306/postify
     username: root
     password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
    host: smtp.gmail.com
    username: youremail@gmail.com
    password: Yout email app credentials
    port: 587
