server:
  port: 8083
  servlet:
    context-path: /api/${spring.application.name}

spring:
  application:
    name: postify
    datasource:
      url: jdbc:mysql://localhost:3306/postify
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          dialeet: org.hibernate.dialect.MySQLDislect
